import "@/app/globals.css";
import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import { CustomProvider } from "./provider";

export const metadata: Metadata = {
  title: "Chitter Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
}
